/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("name.djsweet.query.listener.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":query-tree"))
}

application {
    // Define the main class for the application.
    mainClass.set("name.djsweet.query.listener.app.AppKt")
}
