/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("name.djsweet.thorium.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text:1.10.0")
    implementation(project(":query-tree"))
}

application {
    // Define the main class for the application.
    mainClass.set("name.djsweet.thorium.AppKt")
}
