/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package name.djsweet.thorium

import org.apache.commons.text.WordUtils

fun main() {
    println(WordUtils.capitalize("hello world"))
}
