// SPDX-FileCopyrightText: 2023 Dani Sweet <thorium@djsweet.name>
//
// SPDX-License-Identifier: MIT

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("name.djsweet.thorium.kotlin-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}
