// SPDX-FileCopyrightText: 2023 Dani Sweet <sidereal@djsweet.name>
//
// SPDX-License-Identifier: MIT

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    // Gradle 8.4 really wants to use version 4.1.2, but this version is not compatible with Java 21.
    // So we'll have to ignore the warnings and use 4.2.1 instead, which is known to work correctly on Java 21.
    id("org.gradle.kotlin.kotlin-dsl") version "4.2.1"
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
    mavenCentral()
}

val kotlinVersion = "1.9.21"

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-benchmark-runtime:0.4.7")
}

